name: Snyk Security Scan

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: snyk/actions/setup@master

      - name: Run Snyk test
        env:
          SNYK_TOKEN: snyk_uat.1fcad39e.eyJlIjoxNzgwMTg5MDgwLCJoIjoic255ay5pbyIsImoiOiJBWjVjby1EbFFXV1NmY1YtV1RiOGRBIiwicyI6IlM4TkI2aDZPUWR1c1NQdUxkRG5tT1EiLCJ0aWQiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBIn0.JsNKRlp_e7qufjsbsvaBNYRvFi-Xle4H5YvL3jM7udEjC8UHBD8p2sNMhuNjDmaeiVGZImvW2AUrIic1mpXaAQ
        run: |
          snyk code test


